"""HTML report generation for the Elephant Sighting & Conflict Dashboard.

Produces a single self-contained HTML file (inline CSS, no external
assets) so it can be emailed or printed by forest-department staff
without any dependency on the dashboard being online.
"""

from __future__ import annotations

from datetime import date, datetime
from typing import Optional

import pandas as pd

from core.analytics import compute_kpis, night_day_comparison, severity_distribution
from core.risk_engine import beat_risk_scores

_CSS = """
    body { font-family: 'Segoe UI', Arial, sans-serif; color: #222; margin: 0; background: #f4f6f5; }
    .wrap { max-width: 900px; margin: 0 auto; padding: 32px; }
    .header { background: #1f5f3f; color: #fff; padding: 28px 32px; border-radius: 10px 10px 0 0; }
    .header h1 { margin: 0 0 6px 0; font-size: 26px; }
    .header p { margin: 0; opacity: 0.9; font-size: 14px; }
    .content { background: #fff; padding: 28px 32px; border-radius: 0 0 10px 10px;
               box-shadow: 0 1px 4px rgba(0,0,0,0.08); }
    h2 { font-size: 18px; color: #1f5f3f; border-bottom: 2px solid #e5ece8; padding-bottom: 6px;
         margin-top: 30px; }
    .kpi-grid { display: flex; gap: 16px; flex-wrap: wrap; margin: 16px 0 8px 0; }
    .kpi-card { flex: 1; min-width: 140px; background: #f0f6f2; border: 1px solid #dce8e0;
                border-radius: 8px; padding: 14px 16px; }
    .kpi-card .label { font-size: 12px; color: #567; text-transform: uppercase; letter-spacing: .04em; }
    .kpi-card .value { font-size: 24px; font-weight: 700; color: #1f5f3f; margin-top: 4px; }
    table { width: 100%; border-collapse: collapse; margin: 10px 0 20px 0; font-size: 13px; }
    th, td { text-align: left; padding: 8px 10px; border-bottom: 1px solid #e8ece9; }
    th { background: #f0f6f2; color: #1f5f3f; font-weight: 600; }
    tr:hover { background: #fafcfb; }
    .risk-high { color: #b3261e; font-weight: 700; }
    .risk-med { color: #a86a00; font-weight: 600; }
    .risk-low { color: #1f5f3f; }
    .footer { text-align: center; color: #99a; font-size: 11px; margin-top: 20px; }
    .empty-note { color: #789; font-style: italic; }
"""


def generate_html_report(
    df: pd.DataFrame,
    start_date: Optional[date],
    end_date: Optional[date],
) -> str:
    """Build a complete, styled HTML report for the (filtered) dataset.

    Args:
        df: Filtered/enriched dataframe used to compute all report
            sections. Safe to call with an empty dataframe.
        start_date: Period start to display (typically the min Date in
            the *unfiltered* dataset, or the active filter's start).
        end_date: Period end to display.

    Returns:
        A complete HTML document as a string.
    """
    kpis = compute_kpis(df)
    risk_table = beat_risk_scores(df)
    severity_bands = severity_distribution(df)
    night_day = night_day_comparison(df)

    period_str = _format_period(start_date, end_date)
    night_pct_str = "N/A" if pd.isna(kpis["night_pct"]) else f"{kpis['night_pct']:.1f}%"

    conflict_breakdown_html = _conflict_breakdown_table(df)
    risk_table_html = _risk_table_html(risk_table)
    severity_bands_html = _bands_table_html(severity_bands)
    night_day_html = _night_day_table_html(night_day)

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title>Elephant Monitoring Report</title>
<style>{_CSS}</style>
</head>
<body>
<div class="wrap">
  <div class="header">
    <h1>Elephant Sighting &amp; Conflict Report</h1>
    <p>Period covered: {period_str} &nbsp;|&nbsp; Generated: {datetime.now():%d %b %Y, %H:%M}</p>
  </div>
  <div class="content">

    <h2>Summary</h2>
    <div class="kpi-grid">
      <div class="kpi-card"><div class="label">Total Entries</div><div class="value">{kpis['entries']}</div></div>
      <div class="kpi-card"><div class="label">Conflict Incidents</div><div class="value">{kpis['conflicts']}</div></div>
      <div class="kpi-card"><div class="label">Total Severity</div><div class="value">{kpis['severity']:.1f}</div></div>
      <div class="kpi-card"><div class="label">Night Incidents</div><div class="value">{night_pct_str}</div></div>
    </div>

    <h2>Top Risk Beats</h2>
    {risk_table_html}

    <h2>Severity Distribution</h2>
    {severity_bands_html}

    <h2>Conflict Type Breakdown</h2>
    {conflict_breakdown_html}

    <h2>Night vs. Day Comparison</h2>
    {night_day_html}

    <div class="footer">
      Generated by the Elephant Sighting &amp; Conflict Dashboard. Figures reflect the filters
      active in the dashboard at the time of generation.
    </div>
  </div>
</div>
</body>
</html>"""


def _format_period(start_date: Optional[date], end_date: Optional[date]) -> str:
    if start_date is None or end_date is None or pd.isna(start_date) or pd.isna(end_date):
        return "N/A"
    try:
        return f"{pd.Timestamp(start_date):%d %b %Y} to {pd.Timestamp(end_date):%d %b %Y}"
    except Exception:  # noqa: BLE001 - report generation must never crash
        return "N/A"


def _risk_table_html(risk_table: pd.DataFrame, top_n: int = 10) -> str:
    if risk_table.empty:
        return '<p class="empty-note">No beat data available for the current filters.</p>'

    rows = []
    for _, row in risk_table.head(top_n).iterrows():
        score = row["Risk Score"]
        css_class = "risk-high" if score >= 66 else "risk-med" if score >= 33 else "risk-low"
        night_pct = "N/A" if pd.isna(row["Night %"]) else f"{row['Night %']:.0f}%"
        village_pct = "N/A" if pd.isna(row["Near Village %"]) else f"{row['Near Village %']:.0f}%"
        rows.append(
            "<tr>"
            f"<td>{row['Beat']}</td>"
            f"<td>{int(row['Entries'])}</td>"
            f"<td>{row['Total Severity']:.1f}</td>"
            f"<td>{night_pct}</td>"
            f"<td>{village_pct}</td>"
            f"<td class='{css_class}'>{score:.1f}</td>"
            "</tr>"
        )
    return (
        "<table><thead><tr>"
        "<th>Beat</th><th>Entries</th><th>Total Severity</th>"
        "<th>Night %</th><th>Near Village %</th><th>Risk Score</th>"
        "</tr></thead><tbody>" + "".join(rows) + "</tbody></table>"
    )


def _bands_table_html(bands: pd.DataFrame) -> str:
    if bands.empty:
        return '<p class="empty-note">No severity data available for the current filters.</p>'
    rows = "".join(f"<tr><td>{r.Band}</td><td>{int(r.Count)}</td></tr>" for r in bands.itertuples())
    return (
        "<table><thead><tr><th>Severity Band</th><th>Count</th></tr></thead>"
        f"<tbody>{rows}</tbody></table>"
    )


def _night_day_table_html(night_day: pd.DataFrame) -> str:
    if night_day.empty:
        return '<p class="empty-note">Night/day classification unavailable for the current filters.</p>'
    rows = "".join(
        f"<tr><td>{row['Period']}</td><td>{int(row['Entries'])}</td><td>{row['Avg Severity']:.1f}</td></tr>"
        for _, row in night_day.iterrows()
    )
    return (
        "<table><thead><tr><th>Period</th><th>Entries</th><th>Avg Severity</th></tr></thead>"
        f"<tbody>{rows}</tbody></table>"
    )


def _conflict_breakdown_table(df: pd.DataFrame) -> str:
    if df.empty:
        return '<p class="empty-note">No incident data available for the current filters.</p>'

    zeros = pd.Series(0, index=df.index)
    crop = df.get("Crop Damage", zeros)
    house = df.get("House Damage", zeros)
    injury = df.get("Injury", zeros)
    total_count = df.get("Total Count", zeros)
    counts = {
        "Crop Damage": int((crop > 0).sum()),
        "House Damage": int((house > 0).sum()),
        "Human Injury": int((injury > 0).sum()),
        "Presence Only (no damage)": int(
            ((total_count > 0) & (crop == 0) & (house == 0) & (injury == 0)).sum()
        ),
    }
    rows = "".join(f"<tr><td>{label}</td><td>{count}</td></tr>" for label, count in counts.items())
    return (
        "<table><thead><tr><th>Conflict Type</th><th>Incidents</th></tr></thead>"
        f"<tbody>{rows}</tbody></table>"
    )
